/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type Category = { 'Jackets' : null } |
  { 'Accessories' : null } |
  { 'Hoodies' : null } |
  { 'Trousers' : null };
export interface Order {
  'id' : bigint,
  'createdAt' : bigint,
  'totalAmount' : bigint,
  'shippingAddress' : ShippingAddress,
  'items' : Array<OrderItem>,
  'customerEmail' : string,
}
export interface OrderItem {
  'productId' : bigint,
  'productName' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'description' : string,
  'isFeatured' : boolean,
  'category' : Category,
  'price' : bigint,
}
export interface ShippingAddress {
  'country' : string,
  'city' : string,
  'postalCode' : string,
  'state' : string,
  'addressLine1' : string,
  'addressLine2' : [] | [string],
  'lastName' : string,
  'firstName' : string,
}
export interface _SERVICE {
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getFeaturedProducts' : ActorMethod<[], Array<Product>>,
  'getOrder' : ActorMethod<[bigint], [] | [Order]>,
  'getProductsByCategory' : ActorMethod<[Category], Array<Product>>,
  'getSubscriberCount' : ActorMethod<[], bigint>,
  'placeOrder' : ActorMethod<
    [string, Array<OrderItem>, ShippingAddress],
    bigint
  >,
  'subscribe' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];