/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ShippingAddress = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'postalCode' : IDL.Text,
  'state' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Opt(IDL.Text),
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const OrderItem = IDL.Record({
  'productId' : IDL.Nat,
  'productName' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : IDL.Int,
  'totalAmount' : IDL.Nat,
  'shippingAddress' : ShippingAddress,
  'items' : IDL.Vec(OrderItem),
  'customerEmail' : IDL.Text,
});
export const Category = IDL.Variant({
  'Jackets' : IDL.Null,
  'Accessories' : IDL.Null,
  'Hoodies' : IDL.Null,
  'Trousers' : IDL.Null,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'isFeatured' : IDL.Bool,
  'category' : Category,
  'price' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
  'getProductsByCategory' : IDL.Func([Category], [IDL.Vec(Product)], ['query']),
  'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
  'placeOrder' : IDL.Func(
      [IDL.Text, IDL.Vec(OrderItem), ShippingAddress],
      [IDL.Nat],
      [],
    ),
  'subscribe' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ShippingAddress = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'postalCode' : IDL.Text,
    'state' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Opt(IDL.Text),
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const OrderItem = IDL.Record({
    'productId' : IDL.Nat,
    'productName' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : IDL.Int,
    'totalAmount' : IDL.Nat,
    'shippingAddress' : ShippingAddress,
    'items' : IDL.Vec(OrderItem),
    'customerEmail' : IDL.Text,
  });
  const Category = IDL.Variant({
    'Jackets' : IDL.Null,
    'Accessories' : IDL.Null,
    'Hoodies' : IDL.Null,
    'Trousers' : IDL.Null,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'isFeatured' : IDL.Bool,
    'category' : Category,
    'price' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getFeaturedProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getOrder' : IDL.Func([IDL.Nat], [IDL.Opt(Order)], ['query']),
    'getProductsByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'getSubscriberCount' : IDL.Func([], [IDL.Nat], ['query']),
    'placeOrder' : IDL.Func(
        [IDL.Text, IDL.Vec(OrderItem), ShippingAddress],
        [IDL.Nat],
        [],
      ),
    'subscribe' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };